INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('pirate-kit', 'Pirate Kit', 'Props · Kenney CC0', 'เรือ ปืนใหญ่ หีบสมบัติ และอุปกรณ์ธีมโจรสลัดในชุด Pirate Kit รวม 72 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 89, 'Kenney', '/assets/previews/uploads/pirate-kit-1790017849617-custom.png', 'pirate-kit.zip', 'Props', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 3154665, 'https://kenney.nl/assets/pirate-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('watercraft-kit', 'Watercraft Kit', 'Vehicles · Kenney CC0', 'เรือและยานพาหนะทางน้ำหลายรูปแบบในชุด Watercraft Kit รวม 46 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 109, 'Kenney', '/assets/previews/uploads/watercraft-kit-1790017849647-custom.png', 'watercraft-kit.zip', 'Vehicles', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 1870991, 'https://kenney.nl/assets/watercraft-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('retro-urban-kit', 'Retro Urban Kit', 'Environments · Kenney CC0', 'อาคารและพร็อพเมืองสไตล์ย้อนยุคในชุด Retro Urban Kit รวม 124 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 129, 'Kenney', '/assets/previews/uploads/retro-urban-kit-1790017849674-custom.png', 'retro-urban-kit.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 2161463, 'https://kenney.nl/assets/retro-urban-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('castle-kit', 'Castle Kit', 'Environments · Kenney CC0', 'กำแพง ประตู และหอคอยสำหรับสร้างปราสาทในชุด Castle Kit รวม 76 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 149, 'Kenney', '/assets/previews/uploads/castle-kit-1790017849705-custom.png', 'castle-kit.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 2232589, 'https://kenney.nl/assets/castle-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('tower-defense-kit', 'Tower Defense Kit', 'Props · Kenney CC0', 'ป้อม เส้นทาง และสิ่งก่อสร้างสำหรับเกมป้องกันฐานในชุด Tower Defense Kit รวม 160 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 169, 'Kenney', '/assets/previews/uploads/tower-defense-kit-1790017849755-custom.png', 'tower-defense-kit.zip', 'Props', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 5404433, 'https://kenney.nl/assets/tower-defense-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('nature-kit', 'Nature Kit', 'Environments · Kenney CC0', 'ต้นไม้ หิน ทางเดิน และองค์ประกอบธรรมชาติในชุด Nature Kit รวม 329 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ DAE, FBX, GLB, OBJ, STL พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 189, 'Kenney', '/assets/previews/uploads/nature-kit-1790017849818-custom.png', 'nature-kit.zip', 'Environments', ARRAY['DAE','FBX','GLB','OBJ','STL']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 10537521, 'https://kenney.nl/assets/nature-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('space-kit', 'Space Kit', 'Environments · Kenney CC0', 'ยาน อุปกรณ์ และชิ้นส่วนฉากอวกาศในชุด Space Kit รวม 153 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ DAE, FBX, GLB, OBJ, STL พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 209, 'Kenney', '/assets/previews/uploads/space-kit-1790017849862-custom.png', 'space-kit.zip', 'Environments', ARRAY['DAE','FBX','GLB','OBJ','STL']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 6677531, 'https://kenney.nl/assets/space-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('toy-car-kit', 'Toy Car Kit', 'Vehicles · Kenney CC0', 'รถของเล่นและองค์ประกอบสนามขับรถในชุด Toy Car Kit รวม 157 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 229, 'Kenney', '/assets/previews/uploads/toy-car-kit-1790017849911-custom.png', 'toy-car-kit.zip', 'Vehicles', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 5245353, 'https://kenney.nl/assets/toy-car-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('modular-space-kit', 'Modular Space Kit', 'Environments · Kenney CC0', 'ชิ้นส่วนโมดูลาร์สำหรับต่อสถานีอวกาศในชุด Modular Space Kit รวม 40 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 89, 'Kenney', '/assets/previews/uploads/modular-space-kit-1790017849957-custom.png', 'modular-space-kit.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 6966606, 'https://kenney.nl/assets/modular-space-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('factory-kit', 'Factory Kit', 'Environments · Kenney CC0', 'เครื่องจักรและองค์ประกอบโรงงานในชุด Factory Kit รวม 143 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 109, 'Kenney', '/assets/previews/uploads/factory-kit-1790017849989-custom.png', 'factory-kit.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 4511890, 'https://kenney.nl/assets/factory-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('graveyard-kit', 'Graveyard Kit', 'Environments · Kenney CC0', 'หลุมศพ รั้ว และพร็อพฉากสุสานในชุด Graveyard Kit รวม 91 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 129, 'Kenney', '/assets/previews/uploads/graveyard-kit-1790017850022-custom.png', 'graveyard-kit.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 3623408, 'https://kenney.nl/assets/graveyard-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('fantasy-town-kit', 'Fantasy Town Kit', 'Environments · Kenney CC0', 'อาคารและองค์ประกอบเมืองแฟนตาซีในชุด Fantasy Town Kit รวม 167 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 149, 'Kenney', '/assets/previews/uploads/fantasy-town-kit-1790017850073-custom.png', 'fantasy-town-kit.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 3854691, 'https://kenney.nl/assets/fantasy-town-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('city-kit-commercial', 'City Kit: Commercial', 'Environments · Kenney CC0', 'อาคารย่านร้านค้าและพื้นที่พาณิชย์ในชุด City Kit: Commercial รวม 41 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 169, 'Kenney', '/assets/previews/uploads/city-kit-commercial-1790017850103-custom.png', 'city-kit-commercial.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 4096974, 'https://kenney.nl/assets/city-kit-commercial')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('city-kit-industrial', 'City Kit: Industrial', 'Environments · Kenney CC0', 'อาคารและองค์ประกอบย่านอุตสาหกรรมในชุด City Kit: Industrial รวม 37 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 189, 'Kenney', '/assets/previews/uploads/city-kit-industrial-1790017850138-custom.png', 'city-kit-industrial.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 5045077, 'https://kenney.nl/assets/city-kit-industrial')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('city-kit-suburban', 'City Kit: Suburban', 'Environments · Kenney CC0', 'บ้านและสิ่งก่อสร้างย่านชานเมืองในชุด City Kit: Suburban รวม 40 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 209, 'Kenney', '/assets/previews/uploads/city-kit-suburban-1790017850176-custom.png', 'city-kit-suburban.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 3038740, 'https://kenney.nl/assets/city-kit-suburban')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('mini-dungeon', 'Mini Dungeon', 'Environments · Kenney CC0', 'ห้อง ทางเดิน และของตกแต่งดันเจียนขนาดเล็กในชุด Mini Dungeon รวม 30 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 229, 'Kenney', '/assets/previews/uploads/mini-dungeon-1790017850205-custom.png', 'mini-dungeon.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 1796820, 'https://kenney.nl/assets/mini-dungeon')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('modular-cave-kit', 'Modular Cave Kit', 'Environments · Kenney CC0', 'ผนัง พื้น และชิ้นส่วนสำหรับต่อถ้ำในชุด Modular Cave Kit รวม 40 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 89, 'Kenney', '/assets/previews/uploads/modular-cave-kit-1790017850567-custom.png', 'modular-cave-kit.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 7025078, 'https://kenney.nl/assets/modular-cave-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('animated-characters-retro', 'Animated Characters: Retro', 'Characters · Kenney CC0', 'ตัวละครเคลื่อนไหวสไตล์ย้อนยุคในชุด Animated Characters: Retro รวม 4 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 109, 'Kenney', '/assets/previews/uploads/animated-characters-retro-1790017850597-custom.png', 'animated-characters-retro.zip', 'Characters', ARRAY['FBX']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 706472, 'https://kenney.nl/assets/animated-characters-retro')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('animated-characters-protagonists', 'Animated Characters: Protagonists', 'Characters · Kenney CC0', 'ตัวละครหลักพร้อมไฟล์แอนิเมชันในชุด Animated Characters: Protagonists รวม 4 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 129, 'Kenney', '/assets/previews/uploads/animated-characters-protagonists-1790017850625-custom.png', 'animated-characters-protagonists.zip', 'Characters', ARRAY['FBX']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 581441, 'https://kenney.nl/assets/animated-characters-protagonists')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('animated-characters-survivors', 'Animated Characters: Survivors', 'Characters · Kenney CC0', 'ตัวละครผู้รอดชีวิตพร้อมแอนิเมชันในชุด Animated Characters: Survivors รวม 4 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 149, 'Kenney', '/assets/previews/uploads/animated-characters-survivors-1790017850682-custom.png', 'animated-characters-survivors.zip', 'Characters', ARRAY['FBX']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 718027, 'https://kenney.nl/assets/animated-characters-survivors')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('mini-characters', 'Mini Characters', 'Characters · Kenney CC0', 'ตัวละครขนาดเล็กหลากหลายแบบในชุด Mini Characters รวม 26 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 169, 'Kenney', '/assets/previews/uploads/mini-characters-1790017850713-custom.png', 'mini-characters.zip', 'Characters', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 2403059, 'https://kenney.nl/assets/mini-characters')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('train-kit', 'Train Kit', 'Vehicles · Kenney CC0', 'ขบวนรถไฟ ราง และอุปกรณ์ประกอบในชุด Train Kit รวม 103 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 189, 'Kenney', '/assets/previews/uploads/train-kit-1790017850749-custom.png', 'train-kit.zip', 'Vehicles', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 5266588, 'https://kenney.nl/assets/train-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('platformer-kit', 'Platformer Kit', 'Environments · Kenney CC0', 'พื้น ทางลาด และสิ่งกีดขวางสำหรับเกมแพลตฟอร์มในชุด Platformer Kit รวม 153 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 209, 'Kenney', '/assets/previews/uploads/platformer-kit-1790017850795-custom.png', 'platformer-kit.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 4640135, 'https://kenney.nl/assets/platformer-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('hexagon-kit', 'Hexagon Kit', 'Environments · Kenney CC0', 'แผ่นพื้นที่หกเหลี่ยมและชิ้นส่วนฉากในชุด Hexagon Kit รวม 72 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 229, 'Kenney', '/assets/previews/uploads/hexagon-kit-1790017850830-custom.png', 'hexagon-kit.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 2448931, 'https://kenney.nl/assets/hexagon-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('prototype-kit', 'Prototype Kit', 'Props · Kenney CC0', 'โมเดลต้นแบบหลากหลายประเภทสำหรับทดลองเกมในชุด Prototype Kit รวม 145 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 89, 'Kenney', '/assets/previews/uploads/prototype-kit-1790017850861-custom.png', 'prototype-kit.zip', 'Props', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 2961396, 'https://kenney.nl/assets/prototype-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('minigolf-kit', 'Minigolf Kit', 'Props · Kenney CC0', 'ชิ้นส่วนสนามและอุปกรณ์มินิกอล์ฟในชุด Minigolf Kit รวม 126 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 109, 'Kenney', '/assets/previews/uploads/minigolf-kit-1790017850898-custom.png', 'minigolf-kit.zip', 'Props', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 3163116, 'https://kenney.nl/assets/minigolf-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('holiday-kit', 'Holiday Kit', 'Props · Kenney CC0', 'พร็อพตกแต่งฉากธีมเทศกาลในชุด Holiday Kit รวม 99 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 129, 'Kenney', '/assets/previews/uploads/holiday-kit-1790017850940-custom.png', 'holiday-kit.zip', 'Props', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 4482244, 'https://kenney.nl/assets/holiday-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('coaster-kit', 'Coaster Kit', 'Environments · Kenney CC0', 'รางและชิ้นส่วนเครื่องเล่นรถไฟเหาะในชุด Coaster Kit รวม 183 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ FBX, GLB, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 149, 'Kenney', '/assets/previews/uploads/coaster-kit-1790017850980-custom.png', 'coaster-kit.zip', 'Environments', ARRAY['FBX','GLB','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 6697401, 'https://kenney.nl/assets/coaster-kit')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;

INSERT INTO public.assets (id, title, subtitle, description, price, author, cover, file, category, formats, engines, version, license, file_size_bytes, source_url)
VALUES ('3d-road-tiles', '3D Road Tiles', 'Environments · Kenney CC0', 'แผ่นถนนและทางแยกสำหรับต่อฉากเมืองในชุด 3D Road Tiles รวม 302 โมเดล (นับชื่อโมเดลไม่ซ้ำข้ามฟอร์แมต) รองรับ GLTF, OBJ พร้อมภาพตัวอย่างจาก Kenney และลิงก์ตรวจสอบสิทธิ์ CC0 ที่หน้าต้นฉบับ', 169, 'Kenney', '/assets/previews/uploads/3d-road-tiles-1790017851370-custom.png', '3d-road-tiles.zip', 'Environments', ARRAY['GLTF','OBJ']::text[], ARRAY['Unity','Unreal','Godot']::text[], '1.0.0', 'CC0 1.0', 3683526, 'https://kenney.nl/assets/3d-road-tiles')
ON CONFLICT (id) DO UPDATE SET title=excluded.title, subtitle=excluded.subtitle, description=excluded.description, price=excluded.price, cover=excluded.cover, file=excluded.file, category=excluded.category, formats=excluded.formats, engines=excluded.engines, version=excluded.version, license=excluded.license, file_size_bytes=excluded.file_size_bytes, source_url=excluded.source_url;
